apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api
  namespace: payments
  labels:
    app: payments-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-api
  template:
    metadata:
      labels:
        app: payments-api
    spec:
      containers:
        - name: payments-api
          image: polinux/stress:latest
          command: ["stress"]
          args: ["--vm", "1", "--vm-bytes", "100M", "--vm-hang", "1"]
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe:
            exec:
              command: ["pgrep", "stress"]
            initialDelaySeconds: 5
            periodSeconds: 15
